# Site settings
title: SteelHacks 2016
description: > # this means to ignore newlines until "baseurl:"
  University of Pittsburgh's hackathon! February 19th-21st, 2016.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steelhacks.com" # the base hostname & protocol for your site
twitter_username: steelhacks

# Build settings
markdown: kramdown
